### ISSUE TITLE
Feat: Implement product details page

### ISSUE THREAD

**Issue by jkarenzi** [atlp-rwanda/dynamites-ecomm-fe#101]
### Description
- As a user, I want to be able to see product details of any product of my choice

### Tasks
- [ ] Implement product details UI components
- [ ] Integrate components with backend
- [ ] write appropriate tests

### Definition of Done
- User can view product details of a product
- The page is responsive

**Comment by jkarenzi** [comment]
## Implementation plan

### Day 1: 
- Implement basic UI components
- Integrate components with backend

### Day 2:
- write appropriate tests
- make the page responsive
