### ISSUE TITLE
Fix: Minor Issues in product details page

### ISSUE THREAD

**Issue by jkarenzi** [atlp-rwanda/dynamites-ecomm-fe#115]
### Description

- This is a fix to correct minor issues on the product details page and wishlist page

### Tasks
- [ ] Implement different icon for products that are in the wishlist, compared to those that are not
- [ ] Clicking on a gallery image should bring it to focus
- [ ] Clicking on the product image should navigate one to the details page too
