### ISSUE TITLE
Feat: Integrate payment via momo and stripe

### ISSUE THREAD

**Issue by EddyShimwa** [atlp-rwanda/dynamites-ecomm-fe#123]
### Description
- As a user, I want to be able to make payments of the 

### Tasks
- [ ] Implement payments UI components
- [ ] Integrate components with backend
- [ ] write appropriate tests

### Definition of Done
- User is now able to pay
- The page is responsive

**Comment by EddyShimwa** [comment]
## Implementation plan

### Day 1: 
- Implement basic UI components
- Integrate components with backend

### Day 2:
- write appropriate tests
- make the page responsive
