### ISSUE TITLE
Implement Customer Management

### ISSUE THREAD

**Issue by niyibi250** [atlp-rwanda/dynamites-ecomm-fe#126]
### Description
As an admin, I want to be able to see customer list and be able to manage customer
### Tasks

-  Implement customer management UI components
-  Integrate components with backend
-  Add CRUD operation
-  write appropriate tests

### Definition of Done

- [ ] User can view customer management page
- [ ] user can performe CRUD operation on any customer on page
- [ ] The page is responsive
