### ISSUE TITLE
In App Notification

### ISSUE THREAD

**Issue by niyibi250** [atlp-rwanda/dynamites-ecomm-fe#134]
### Description
As an admin, I want to be able to see category dashboard with their description. so that I can edit and delete category
### Tasks

-  Design the Notification UI
-  Fetch relevant data from backend and integrate it with the frontend UI

### Definition of Done

- [ ] user can see notification
- [ ] Notification data is fetched from the backend
- [ ] user can delete and view notification
