### ISSUE TITLE
Feature: Implimenting Footer 

### ISSUE THREAD

**Issue by 13XAVI** [atlp-rwanda/dynamites-ecomm-fe#29]
## Description
As a user of the web application,
I want the footer to become visible only when I scroll to the bottom of the page, using redux tool kit  as state manager and is accessible when needed.

## Acceptance Criteria:
- [ ] The footer should be hidden when the user first loads the page.
- [ ] The footer should appear when the user scrolls to the bottom of the page.
- [ ] The footer should disappear when the user scrolls up from the bottom of the page.

**Comment by 13XAVI** [comment]
## Implementation Plan for Login Feature with Redux Toolkit and TailwindCSS
### 1. Deliverables by End of Week:
- [ ] Working  Footer component that is responsive on both Mobile and Deskrop
- [ ] Redux Toolkit setup for state management.

### 2. Schedule of Implementation:
#### Day 1: Wednesday (06/19/2024)
 Morning:
Rebase the  Project
set Up Redux Tool Kit
Afternoon:
Create footer in  typescript and   state manager using Redux
#### Day 2: Thursday (06/20/2024)
Morning: Styling using Tailwind and  make  it  responsive
Afternoon: Push my codes
### 3. Additional Notes:
Regular reviews and testing at the end of each day to ensure progress and address issues.
Collaborate and  communicate within the teammates.
### 4. External Services or Libraries:
React
Redux Toolkit
TailwindCSS
Router DOM
Axios
