### ISSUE TITLE
Ch:  Setup Project Redux

### ISSUE THREAD

**Issue by 13XAVI** [atlp-rwanda/dynamites-ecomm-fe#32]
### Build a setup  Project  
 As developer i want to configure Project setup  for  E-commerce front End
### Task to be completed

- [ ] Setup Config.ts  to define  use  colors and fonts
- [ ] Configure Router Dom
- [ ] Configure Redux toolkit
