### ISSUE TITLE
Chore: Set up tailwind config

### ISSUE THREAD

**Issue by jkarenzi** [atlp-rwanda/dynamites-ecomm-fe#34]
### Description:
As a developer, I want to be able to use custom colors, breakpoints and font families in my styles.

### Tasks:

- [ ] add custom colors to tailwind config
- [ ] add breakpoints for responsivity on varying screen sizes
- [ ] add font families

### Definition of Done
- Config file contains all colors to be used in development
- Config file contains multiple breakpoints for varying screen sizes
- Config file contains custom font families
