### ISSUE TITLE
Chore: Configure routes using React Router Dom

### ISSUE THREAD

**Issue by wayneleon1** [atlp-rwanda/dynamites-ecomm-fe#36]
### Description:

As a developer, I want to be able to configure routes in my React application using React Router Dom so that I can navigate between different pages seamlessly.

#### Tasks:

- [ ] Configure Basic Routes
- [ ] Implement Nested Routes
- [ ] 404 Page Not Found Handling

#### Definition of Done

- [ ] Create a basic structure for the routes
- [ ] Define a parent route for the HomeRoutes
- [ ] Create a 404 Page Not Found component
