### ISSUE TITLE
Feat: Integrate Google Auth

### ISSUE THREAD

**Issue by jkarenzi** [atlp-rwanda/dynamites-ecomm-fe#46]
### Description
- As a user, I want to be able to log into the application using google authentication so as to easily access the application without having to go through a lengthy signup process.

### Tasks
- [ ] Integrate signup and login pages with google auth
- [ ] Write relevant tests

### Acceptance Criteria:
- [ ] User can signup and login with google auth
- [ ] Tests are passing
