### ISSUE TITLE
Feat: Implement shop page 

### ISSUE THREAD

**Issue by jkarenzi** [atlp-rwanda/dynamites-ecomm-fe#90]
## Description/Stories
- As a buyer, I want to be able to see all products on the shop page, and search and filter for a specific product that I need.

## Tasks
- [ ] Implement shop page ui components
- [ ] Implement search and filter functionality
- [ ] Write appropriate tests

## Definition of Done
- Buyer is able to view all products on shop page
- Buyer is able to filter and search for a specific product
- Pagination is implemented

**Comment by jkarenzi** [comment]
## Implementation plan

### Day 1
- Complete initial component design

### Day 2
- Implement search and filter functionality
- Integrate the design with the backend

### Day 3
- write appropriate tests
