### ISSUE TITLE
Feat: Wishlist

### ISSUE THREAD

**Issue by jkarenzi** [atlp-rwanda/dynamites-ecomm-fe#96]
### Description

- As a buyer, I want to be able to add items to my wishlist, remove items items from my wishlist and fetch all items in my wishlist

### Tasks
- [ ] Implement wishlist page UI components
- [ ] Implement functionality for fetching items, adding items and removing items to and from the wishlist

### Definition of Done
- [ ] User can add any item to their wishlist
- [ ] User can remove item from wishlist
- [ ] User can get all items in their wishlist

**Comment by jkarenzi** [comment]
## Implementation plan

### Day 1:
- Implement UI components
- Integrate the UI components with the backend
- Implement pagination if necessary
- Write appropriate tests
